/*******************************************************/
/*      "C" Language Integrated Production System      */
/*                                                     */
/*             CLIPS Version 6.40  07/17/18            */
/*                                                     */
/*          MISCELLANEOUS FUNCTIONS HEADER FILE        */
/*******************************************************/

/*************************************************************/
/* Purpose:                                                  */
/*                                                           */
/* Principal Programmer(s):                                  */
/*      Gary D. Riley                                        */
/*                                                           */
/* Contributing Programmer(s):                               */
/*                                                           */
/* Revision History:                                         */
/*                                                           */
/*      6.23: Correction for FalseSymbol/TrueSymbol. DR0859  */
/*                                                           */
/*            Corrected compilation errors for files         */
/*            generated by constructs-to-c. DR0861           */
/*                                                           */
/*            Changed name of variable exp to theExp         */
/*            because of Unix compiler warnings of shadowed  */
/*            definitions.                                   */
/*                                                           */
/*      6.24: Removed CONFLICT_RESOLUTION_STRATEGIES,        */
/*            DYNAMIC_SALIENCE, INCREMENTAL_RESET,           */
/*            LOGICAL_DEPENDENCIES, IMPERATIVE_METHODS       */
/*            INSTANCE_PATTERN_MATCHING,                     */
/*            IMPERATIVE_MESSAGE_HANDLERS, and               */
/*            AUXILIARY_MESSAGE_HANDLERS compilation flags.  */
/*                                                           */
/*            Renamed BOOLEAN macro type to intBool.         */
/*                                                           */
/*      6.30: Support for long long integers.                */
/*                                                           */
/*            Used gensprintf instead of sprintf.            */
/*                                                           */
/*            Removed conditional code for unsupported       */
/*            compilers/operating systems.                   */
/*                                                           */
/*            Renamed EX_MATH compiler flag to               */
/*            EXTENDED_MATH_FUNCTIONS.                       */
/*                                                           */
/*            Combined BASIC_IO and EXT_IO compilation       */
/*            flags into the IO_FUNCTIONS compilation flag.  */
/*                                                           */
/*            Removed code associated with HELP_FUNCTIONS    */
/*            and EMACS_EDITOR compiler flags.               */
/*                                                           */
/*            Added operating-system function.               */
/*                                                           */
/*            Added new function (for future use).           */
/*                                                           */
/*            Added const qualifiers to remove C++           */
/*            deprecation warnings.                          */
/*                                                           */
/*      6.31: Added local-time and gm-time functions.        */
/*                                                           */
/*      6.40: Refactored code to reduce header dependencies  */
/*            in sysdep.c.                                   */
/*                                                           */
/*            Removed LOCALE definition.                     */
/*                                                           */
/*            Pragma once and other inclusion changes.       */
/*                                                           */
/*            Added support for booleans with <stdbool.h>.   */
/*                                                           */
/*            Removed use of void pointers for specific      */
/*            data structures.                               */
/*                                                           */
/*            UDF redesign.                                  */
/*                                                           */
/*            Added get-error, set-error, and clear-error    */
/*            functions.                                     */
/*                                                           */
/*************************************************************/

#ifndef _H_miscfun

#pragma once

#define _H_miscfun

void MiscFunctionDefinitions(Environment *);
void ExitCommand(Environment *theEnv, UDFContext *context, UDFValue *ret);
void CreateFunction(Environment *theEnv, UDFContext *context, UDFValue *ret);
void SetgenFunction(Environment *theEnv, UDFContext *context, UDFValue *ret);
void GensymFunction(Environment *theEnv, UDFContext *context, UDFValue *ret);
void GensymStarFunction(Environment *theEnv, UDFContext *context, UDFValue *ret);
void RandomFunction(Environment *theEnv, UDFContext *context, UDFValue *ret);
void SeedFunction(Environment *theEnv, UDFContext *context, UDFValue *ret);
void LengthFunction(Environment *theEnv, UDFContext *context, UDFValue *ret);
void ConserveMemCommand(Environment *theEnv, UDFContext *context, UDFValue *ret);
void ReleaseMemCommand(Environment *theEnv, UDFContext *context, UDFValue *ret);
void MemUsedCommand(Environment *theEnv, UDFContext *context, UDFValue *ret);
void MemRequestsCommand(Environment *theEnv, UDFContext *context, UDFValue *ret);
void OptionsCommand(Environment *theEnv, UDFContext *context, UDFValue *ret);
void OperatingSystemFunction(Environment *theEnv, UDFContext *context, UDFValue *ret);
void ExpandFuncCall(Environment *theEnv, UDFContext *context, UDFValue *ret);
void DummyExpandFuncMultifield(Environment *theEnv, UDFContext *context, UDFValue *ret);
void CauseEvaluationError(Environment *theEnv, UDFContext *context, UDFValue *ret);
void SetSORCommand(Environment *theEnv, UDFContext *context, UDFValue *ret);
void GetSORCommand(Environment *theEnv, UDFContext *context, UDFValue *ret);
void GetFunctionRestrictions(Environment *theEnv, UDFContext *context, UDFValue *ret);
void AproposCommand(Environment *theEnv, UDFContext *context, UDFValue *ret);
void GensymStar(Environment *, UDFValue *);
void GetFunctionListFunction(Environment *theEnv, UDFContext *context, UDFValue *ret);
void FuncallFunction(Environment *theEnv, UDFContext *context, UDFValue *ret);
void NewFunction(Environment *theEnv, UDFContext *context, UDFValue *ret);
void CallFunction(Environment *theEnv, UDFContext *context, UDFValue *ret);
void TimerFunction(Environment *theEnv, UDFContext *context, UDFValue *ret);
void TimeFunction(Environment *theEnv, UDFContext *context, UDFValue *ret);
void SystemCommand(Environment *theEnv, UDFContext *context, UDFValue *ret);
void LocalTimeFunction(Environment *theEnv, UDFContext *context, UDFValue *ret);
void GMTimeFunction(Environment *theEnv, UDFContext *context, UDFValue *ret);
void GetErrorFunction(Environment *theEnv, UDFContext *context, UDFValue *ret);
void ClearErrorValue(Environment *);
void ClearErrorFunction(Environment *theEnv, UDFContext *context, UDFValue *ret);
void SetErrorFunction(Environment *theEnv, UDFContext *context, UDFValue *ret);
void SetErrorValue(Environment *, TypeHeader *);
void VoidFunction(Environment *theEnv, UDFContext *context, UDFValue *ret);

#endif /* _H_miscfun */






